language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zongzijie"
  - git config user.email "328308304@qq.com"
  - git add .
  - git commit -m "travis auto update docs"
  - git push --force --quiet "https://${githubblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/zongzijie/zongzijie.github.io.git